# Uncomment the next line to define a global platform for your project
platform :ios, '10.3'

target 'Sulchedule' do
  # Comment the next line if you're not using Swift and don't want to use dynamic frameworks
  use_frameworks!

  # Pods for Sulchedule
pod 'Google-Mobile-Ads-SDK'

  target 'SulcheduleUITests' do
    inherit! :search_paths
    # Pods for testing
  end

end
